module.exports = {
    'env': {
        'es6': true
    },

    'plugins': ['react'],

    'extends': ['plugin:react/recommended'],

    'parserOptions': {
        'sourceType': 'module',
        'ecmaFeatures': {
            'jsx': true,
            'experimentalObjectRestSpread': true
        }
    },

    'rules': {
        'array-bracket-spacing': ['error', 'never'],
        'array-callback-return': 'error',
        'arrow-spacing': ['error', {'before': true, 'after': true}],
        'block-scoped-var': 'warn',
        'block-spacing': ['error', 'always'],
        'brace-style': ['error', '1tbs', {'allowSingleLine': true}],
        'callback-return': 'warn',
        'camelcase': ['error', {'properties': 'never'}],
        'comma-dangle': ['error', 'never'],
        'comma-spacing': ['error', {'before': false, 'after': true}],
        'comma-style': ['error', 'last'],
        'complexity': 'warn',
        'computed-property-spacing': ['error', 'never'],
        'consistent-return': 'warn',
        'constructor-super': 'error',
        'curly': 'error',
        'dot-location': ['error', 'property'],
        'eol-last': 'warn',
        'eqeqeq': ['warn', 'always'],
        'func-call-spacing': ['error', 'never'],
        'jsx-quotes': ['error', 'prefer-single'],
        'generator-star-spacing': ['error', {'before': false, 'after': true}],
        'guard-for-in': 'error',
        'handle-callback-err': 'warn',
        'indent': ['error', 4, {'SwitchCase': 1}],
        'key-spacing': ['error', {'beforeColon': false, 'afterColon': true}],
        'keyword-spacing': ['error', {'before': true, 'after': true}],
        'linebreak-style': ['error', 'unix'],
        'max-depth': ['warn', {'maximum': 5}],
        'max-len': ['warn', {'code': 120, 'ignoreUrls': true}],
        'new-cap': 'error',
        'new-parens': 'error',
        'no-array-constructor': 'warn',
        'no-bitwise': 'error',
        'no-caller': 'error',
        'no-case-declarations': 'error',
        'no-class-assign': 'error',
        'no-cond-assign': 'error',
        'no-confusing-arrow': 'warn',
        'no-const-assign': 'error',
        'no-constant-condition': 'error',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-delete-var': 'error',
        'no-div-regex': 'warn',
        'no-dupe-args': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-duplicate-imports': 'error',
        'no-empty': 'error',
        'no-empty-character-class': 'error',
        'no-empty-pattern': 'error',
        'no-eq-null': 'error',
        'no-eval': 'warn',
        'no-ex-assign': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'warn',
        'no-extra-boolean-cast': 'error',
        'no-extra-label': 'error',
        'no-extra-semi': 'error',
        'no-fallthrough': 'error',
        'no-floating-decimal': 'error',
        'no-func-assign': 'error',
        'no-global-assign': 'warn',
        'no-implicit-coercion': 'warn',
        'no-implicit-globals': 'warn',
        'no-implied-eval': 'warn',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'error',
        'no-invalid-this': 'warn',
        'no-irregular-whitespace': 'error',
        'no-iterator': 'error',
        'no-label-var': 'error',
        'no-labels': 'error',
        'no-lonely-if': 'warn',
        'no-loop-func': 'error',
        'no-mixed-spaces-and-tabs': 'error',
        'no-multi-spaces': 'error',
        'no-multiple-empty-lines': 'error',
        'no-negated-condition': 'warn',
        'no-negated-in-lhs': 'error',
        'no-nested-ternary': 'warn',
        'no-new': 'error',
        'no-new-func': 'warn',
        'no-new-object': 'warn',
        'no-new-require': 'error',
        'no-new-symbol': 'error',
        'no-new-wrappers': 'error',
        'no-obj-calls': 'error',
        'no-octal': 'error',
        'no-octal-escape': 'error',
        'no-param-reassign': 'warn',
        'no-path-concat': 'warn',
        'no-proto': 'error',
        'no-redeclare': 'error',
        'no-regex-spaces': 'error',
        'no-restricted-syntax': ['error', 'WithStatement'],
        'no-return-assign': ['error', 'always'],
        'no-script-url': 'error',
        'no-self-assign': 'error',
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-shadow': 'warn',
        'no-shadow-restricted-names': 'error',
        'no-sparse-arrays': 'error',
        'no-this-before-super': 'error',
        'no-throw-literal': 'warn',
        'no-trailing-spaces': 'error',
        'no-undef': 'error',
        'no-undef-init': 'error',
        'no-unexpected-multiline': 'error',
        'no-unmodified-loop-condition': 'error',
        'no-unneeded-ternary': 'error',
        'no-unreachable': 'error',
        'no-unsafe-finally': 'error',
        'no-unused-expressions': 'error',
        'no-unused-labels': 'error',
        'no-unused-vars': 'error',
        'no-use-before-define': 'warn',
        'no-useless-call': 'error',
        'no-useless-concat': 'error',
        'no-useless-constructor': 'error',
        'no-useless-escape': 'error',
        'no-var': 'error',
        'no-void': 'error',
        'no-whitespace-before-property': 'error',
        'no-with': 'error',
        'object-curly-spacing': ['error', 'never'],
        'quotes': ['error', 'single'],
        'radix': 'warn',
        'semi': ['error', 'always'],
        'semi-spacing': 'error',
        'space-before-blocks': 'error',
        'space-before-function-paren': [2, {'anonymous': 'always', 'named': 'never'}],
        'space-in-parens': ['error', 'never'],
        'space-infix-ops': 'error',
        'space-unary-ops': 'error',
        'spaced-comment': 'warn',
        'strict': 'warn',
        'prefer-arrow-callback': 'warn',
        'prefer-const': 'error',
        'prefer-template': 'warn',
        'require-yield': 'warn',
        'template-curly-spacing': ['error', 'never'],
        'use-isnan': 'error',
        'valid-jsdoc': ['warn', {'requireParamDescription': false, 'requireReturnDescription': false}],
        'valid-typeof': 'error',
        'wrap-iife': ['error', 'inside'],
        'yield-star-spacing': ['error', {'before': false, 'after': true}]
    }
};
