module.exports = {
    'env': {
        'es6': true
    },

    'rules': {
        'indent': ['error', 'tab', {'SwitchCase': 1}],
        'linebreak-style': ['error', 'unix'],
        'quotes': 'off',
        'semi': ['error', 'always'],
        'brace-style': ['error', '1tbs', {'allowSingleLine': true}],
        'camelcase': ['error', {'properties': 'never'}],
        'func-style': 'off',
        'lines-around-comment': 'off',
        'newline-after-var': 'off',
        'no-eval': 'warn',
        'no-self-compare': 'error',
        'no-shadow': 'warn',
        'no-underscore-dangle': 'off',
        'no-use-before-define': 'warn',
        'one-var-declaration-per-line': 'off',
        'radix': 'warn',
        'require-jsdoc': 'off',
        'space-before-function-paren': [2, {'anonymous': 'always', 'named': 'never'}],
        'spaced-comment': 'warn',
        'strict': 'off',
        'valid-jsdoc': ['warn', {'requireParamDescription': false, 'requireReturnDescription': false}],
        'wrap-iife': ['error', 'inside'],
        'comma-dangle': ['error', 'never'],
        'no-debugger': 'error',
        'no-dupe-args': 'error',
        'no-dupe-keys': 'error',
        'no-empty-character-class': 'error',
        'no-ex-assign': 'error',
        'no-extra-semi': 'error',
        'no-func-assign': 'error',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'error',
        'no-negated-in-lhs': 'error',
        'no-obj-calls': 'error',
        'no-sparse-arrays': 'error',
        'no-unexpected-multiline': 'error',
        'no-unreachable': 'error',
        'use-isnan': 'error',
        'valid-typeof': 'error',
        'block-scoped-var': 'warn',
        'curly': 'error',
        'dot-location': ['error', 'property'],
        'no-case-declarations': 'error',
        'no-empty-pattern': 'error',
        'no-eq-null': 'error',
        'no-extra-label': 'error',
        'no-implicit-coercion': 'warn',
        'no-implicit-globals': 'warn',
        'no-return-assign': ['error', 'always'],
        'no-throw-literal': 'warn',
        'no-unused-labels': 'error',
        'no-useless-call': 'error',
        'no-void': 'error',
        'array-bracket-spacing': ['error', 'never'],
        'computed-property-spacing': ['error', 'never'],
        'consistent-this': ['warn', 'self'],
        'max-len': ['warn', {'code': 120, 'ignoreUrls': true}],
        'no-multiple-empty-lines': 'error',
        'no-whitespace-before-property': 'error',
        'object-curly-spacing': ['error', 'never'],
        'quote-props': ['warn', 'consistent'],
        'complexity': 'warn',
        'vars-on-top': 'off',
        'wrap-regex': 'off',
        'space-in-parens': ['error', 'never'],
        'sort-vars': 'off',
        'semi-spacing': 'error',
        'operator-linebreak': 'off',
        'operator-assignment': 'off',
        'no-labels': 'error',
        'guard-for-in': 'error',
        'handle-callback-err': 'warn',
        'id-length': 'off',
        'id-blacklist': 'off',
        'id-match': 'off',
        'init-declarations': 'off',
        'max-depth': ['warn', {'maximum': 5}],
        'no-with': 'error',
        'no-warning-comments': 'off',
        'no-unused-expressions': 'error',
        'no-unneeded-ternary': 'error',
        'no-unmodified-loop-condition': 'error',
        'no-alert': 'off',
        'no-array-constructor': 'off',
        'no-bitwise': 'off',
        'no-caller': 'off',
        'no-catch-shadow': 'off',
        'no-class-assign': 'error',
        'no-cond-assign': 'error',
        'no-confusing-arrow': 'off',
        'no-console': 'off',
        'no-const-assign': 'error',
        'no-constant-condition': 'error',
        'no-continue': 'off',
        'no-control-regex': 'error',
        'no-delete-var': 'error',
        'no-div-regex': 'off',
        'no-dupe-class-members': 'error',
        'no-duplicate-case': 'error',
        'no-duplicate-imports': 'off',
        'no-else-return': 'off',
        'no-empty': 'error',
        'no-empty-function': 'off',
        'no-extend-native': 'off',
        'no-extra-bind': 'off',
        'no-extra-boolean-cast': 'error',
        'no-extra-parens': 'off',
        'no-fallthrough': 'error',
        'no-floating-decimal': 'off',
        'no-implied-eval': 'off',
        'no-inline-comments': 'off',
        'no-invalid-this': 'off',
        'no-iterator': 'off',
        'no-label-var': 'off',
        'no-lone-blocks': 'off',
        'no-lonely-if': 'off',
        'no-loop-func': 'off',
        'no-mixed-requires': 'off',
        'no-mixed-spaces-and-tabs': 'error',
        'no-multi-spaces': 'off',
        'no-multi-str': 'off',
        'no-native-reassign': 'off',
        'no-negated-condition': 'off',
        'no-nested-ternary': 'off',
        'no-new': 'off',
        'no-new-func': 'off',
        'no-new-object': 'off',
        'no-new-require': 'off',
        'no-new-symbol': 'error',
        'no-new-wrappers': 'off',
        'no-octal': 'error',
        'no-octal-escape': 'off',
        'no-param-reassign': 'off',
        'no-path-concat': 'off',
        'no-plusplus': 'off',
        'no-process-env': 'off',
        'no-process-exit': 'off',
        'no-proto': 'off',
        'no-redeclare': 'error',
        'no-regex-spaces': 'error',
        'no-restricted-globals': 'off',
        'no-restricted-imports': 'off',
        'no-restricted-modules': 'off',
        'no-restricted-syntax': 'off',
        'no-script-url': 'off',
        'no-self-assign': 'error',
        'no-sequences': 'off',
        'no-shadow-restricted-names': 'off',
        'no-spaced-func': 'off',
        'no-sync': 'off',
        'no-ternary': 'off',
        'no-trailing-spaces': 'off',
        'no-this-before-super': 'error',
        'no-undef': 'error',
        'no-undef-init': 'off',
        'no-undefined': 'off',
        'no-unused-vars': 'error',
        'no-useless-concat': 'off',
        'no-useless-constructor': 'off',
        'no-useless-escape': 'off',
        'no-var': 'off',
        'no-magic-numbers': 'off',
        'array-callback-return': 'off',
        'arrow-body-style': 'off',
        'arrow-parens': 'off',
        'arrow-spacing': 'off',
        'accessor-pairs': 'off',
        'block-spacing': 'off',
        'callback-return': 'off',
        'comma-spacing': 'off',
        'comma-style': 'off',
        'consistent-return': 'off',
        'constructor-super': 'error',
        'default-case': 'off',
        'dot-notation': 'off',
        'eol-last': 'off',
        'eqeqeq': 'off',
        'func-names': 'off',
        'generator-star-spacing': 'off',
        'global-require': 'off',
        'jsx-quotes': 'off',
        'key-spacing': 'off',
        'keyword-spacing': 'off',
        'max-nested-callbacks': 'off',
        'max-params': 'off',
        'max-statements': 'off',
        'max-statements-per-line': 'off',
        'new-cap': 'off',
        'new-parens': 'off',
        'newline-before-return': 'off',
        'newline-per-chained-call': 'off',
        'object-shorthand': 'off',
        'one-var': 'off',
        'padded-blocks': 'off',
        'prefer-arrow-callback': 'off',
        'prefer-const': 'off',
        'prefer-reflect': 'off',
        'prefer-rest-params': 'off',
        'prefer-spread': 'off',
        'prefer-template': 'off',
        'require-yield': 'off',
        'sort-imports': 'off',
        'space-before-blocks': 'off',
        'space-infix-ops': 'off',
        'space-unary-ops': 'off',
        'template-curly-spacing': 'off',
        'yield-star-spacing': 'off',
        'yoda': 'off'
    }
};
